= Webdev toolkit container

== Description

This notebook is based on continuumio/miniconda, with the following
modifications:

- You are expected to mount a volume with project source code at /tmp
- entrypoint.sh creates `someuser` and gives it the uid of the /tmp directory
  unless it is owned by root.

The goal is to provide a reasonable common baseline of tools and to reduce
problems associated with file permissions.
This part is the most problematic, since letting the process run as room in the container means all created files belong to root.
To mitigate this problem, the container will attempt create a user with the same UID as the current directory and will use that user to run the command within the container.
If the current directory is owned by root, no change is needed.
Every attempt is made to keep typical UID space available.
It is not a flawless strategy but works in most cases.


== Example for standard use:

Standard use involves starting an ephemeral container that will delete itself
after it finishes running.

```[language=bash]
docker run --rm -v $(pwd):/tmp cajanzen/webdev-toolkit
```


== Example usage for leaving the container running

An alternative use is to start the container but detach from it, leaving it
running in the background doing nothing (sleep infinity).

```
docker run --name toolkit -v $(pwd):/tmp -d cajanzen/webdev-toolkit sleep infinity
```

This is useful if you don't need to change the mounted volume, and you plan to
re-enter the container often.
You can enter the sleeping container as follows:

```
docker exec -it toolkit login
```

Note that if you put a container into the background, you will need to manually stop it and delete it.

```
docker stop toolkit
docker rm toolkit -v
```

(the -v deletes any named volumes the container might have had)


